const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console,URL,Date,setTimeout,clearTimeout,AbortController});
vm.runInContext(`const COUPON_FEED={updatedAt:new Date().toISOString(),offers:[]};
 const METHODS={card:{r:'0.5%',conditions:[],src:[],rankable:true},paypay:{n:'PayPay',r:'1.5%',conditions:[],rankable:true}};
 function configuredRate(s){return parseFloat(s)||0;}`,ctx);
vm.runInContext(fs.readFileSync('scripts/coupon_runtime.js','utf8'),ctx);
function run(src){return vm.runInContext(src,ctx);}
run(`const store={store:'テスト店',aliases:[],payments:[{n:'PayPay',r:'1.5%',rankable:true}]};
const start=new Date(Date.now()-86400000).toISOString().slice(0,10),end=new Date(Date.now()+86400000).toISOString().slice(0,10);
const a={id:'a',provider:'paypay',brand:'テスト店',rate:10,maxBonus:100,start,end,termsVerified:true};
const b={...a,id:'b',audience:'lyp',rate:5,maxBonus:300};COUPON_FEED.offers=[a,b];`);
assert.equal(run('couponStoreOffer(store,"paypay")'),null,'must not presume eligibility');
run('couponState(store).checked={a:true,b:true};');
assert.equal(run('couponStoreOffer(store,"paypay")'),null,'capped coupons need an amount');
run('couponState(store).amount=1000');assert.equal(run('couponStoreOffer(store,"paypay").id'),'a');
run('couponState(store).amount=5000');assert.equal(run('couponStoreOffer(store,"paypay").id'),'b','choose actual points not nominal percent');
run('refreshCouponBonus(store)');assert.equal(run('comparisonRate(store.payments[0])'),6.5,'only one coupon, not both');
assert.equal(run('couponPoints({...a,termsVerified:false},1000)'),0);
assert.equal(run('couponPoints({...a,minSpend:2000},1000)'),0);
assert.equal(run('couponPoints(a,19)'),1,'fractional point floor');
assert.equal(run('couponLive({...a,end:"2000-01-01"})'),false);
assert.equal(run('couponLive({...a,start:"2999-01-01"})'),false);
assert.equal(run('couponLive({...a,checkedAt:"2000-01-01T00:00:00Z"})'),false);
assert.equal(run('couponMatches({store:"松屋",aliases:[]},{brand:"松屋フーズ",aliases:[]})'),false,'no guessed group aliases');
assert.equal(run('couponSafeLink("javascript:alert(1)")'),'');
run('COUPON_FEED.offers=[{provider:"vpass",brand:"ジョリーパスタ",rate:10}];const jolly={store:"ジョリーパスタ",aliases:["ジョリパ"],payments:[{n:"PayPay",r:"1.5%",rankable:true}]};refreshCouponBonus(jolly);');
assert.equal(run('comparisonRate(jolly.payments.find(p=>p.id==="vpassCouponCard"))'),10.5);
run('refreshCouponBonus(jolly)');assert.equal(run('jolly.payments.filter(p=>p.id==="vpassCouponCard").length'),1);
console.log('15 coupon eligibility, expiry, caps, matching and Jolly regression checks passed');
