const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const ctx=vm.createContext({console,URL,Date,setTimeout,clearTimeout,AbortController});
vm.runInContext(`const COUPON_FEED={updatedAt:new Date().toISOString(),offers:[]};
 const METHODS={card:{r:'0.5%',conditions:[],src:[],rankable:true},paypay:{n:'PayPay',r:'1.5%',conditions:[],rankable:true}};
 function configuredRate(s){return parseFloat(s)||0;}`,ctx);
vm.runInContext(fs.readFileSync('scripts/coupon_runtime.js','utf8'),ctx);
function run(src){return vm.runInContext(src,ctx);}
run(`const store={store:'テスト店',aliases:[],payments:[{id:'paypay',n:'PayPay',r:'1.5%',rankable:true}]};
const start=new Date(Date.now()-86400000).toISOString().slice(0,10),end=new Date(Date.now()+86400000).toISOString().slice(0,10);
const a={id:'a',provider:'paypay',brand:'テスト店',rate:10,maxBonus:100,start,end,termsVerified:true};
const b={...a,id:'b',audience:'lyp',rate:5,maxBonus:300};COUPON_FEED.offers=[a,b];`);
assert.equal(run('couponStoreOffer(store,"paypay")'),null,'must not presume eligibility');
run('couponState(store).checked={a:true,b:true};');
assert.equal(run('couponStoreOffer(store,"paypay")'),null,'capped campaigns need an amount');
run('couponState(store).amount=1000');assert.equal(run('couponStoreOffer(store,"paypay").id'),'a');
run('couponState(store).amount=5000');assert.equal(run('couponStoreOffer(store,"paypay").id'),'b','choose actual points not nominal percent');
run('refreshCouponBonus(store)');assert.equal(run('comparisonRate(store.payments[0])'),6.5,'only one PayPay campaign, not both');
assert.equal(run('couponPoints({...a,termsVerified:false},1000)'),0);
assert.equal(run('couponPoints({...a,minSpend:2000},1000)'),0);
assert.equal(run('couponPoints(a,19)'),1,'fractional point floor');
assert.equal(run('couponLive({...a,end:"2000-01-01"})'),false);
assert.equal(run('couponLive({...a,start:"2999-01-01"})'),false);
assert.equal(run('couponLive({...a,checkedAt:"2000-01-01T00:00:00Z"})'),false);
assert.equal(run('couponMatches({store:"松屋",aliases:[]},{brand:"松屋フーズ",aliases:[]})'),false,'no guessed group aliases');
assert.equal(run('couponSafeLink("javascript:alert(1)")'),'');
assert.ok(run('couponSafeLink("https://media.aupay.wallet.auone.jp/articles/5226")'));
assert.equal(run('couponPaymentProvider({id:"rakuten",n:"楽天ペイ"})'),'rakuten');
assert.equal(run('couponPaymentProvider({id:"dpay",n:"d払い"})'),'dpay');
assert.equal(run('couponPaymentProvider({id:"aupay",n:"au PAY"})'),'aupay');
assert.equal(run('couponPaymentProvider({id:"aeonGroup",n:"AEON Pay"})'),'aeonpay');
assert.equal(run('couponPaymentProvider({id:"famipay",n:"FamiPay"})'),'famipay');
run('COUPON_FEED.offers=[{provider:"vpass",brand:"ジョリーパスタ",rate:10}];const jolly={store:"ジョリーパスタ",aliases:["ジョリパ"],payments:[{id:"paypay",n:"PayPay",r:"1.5%",rankable:true}]};refreshCouponBonus(jolly);');
assert.equal(run('comparisonRate(jolly.payments.find(p=>p.id==="vpassCouponCard"))'),10.5);
run('refreshCouponBonus(jolly)');assert.equal(run('jolly.payments.filter(p=>p.id==="vpassCouponCard").length'),1);
run(`COUPON_FEED.offers=[{id:'au1',provider:'aupay',brand:'上島珈琲店',fixedBonus:100,bonusKind:'discount',minSpend:700,maxBonus:100,start,end,termsVerified:true,checkedAt:new Date().toISOString()}];
 const ucc={store:'上島珈琲店',aliases:[],payments:[{id:'aupay',n:'au PAY',r:'0.5%',rankable:true}]};
 couponState(ucc).amount=2000;couponState(ucc).checked={au1:true};refreshCouponBonus(ucc);`);
assert.equal(run('comparisonRate(ucc.payments[0])'),5.5,'fixed 100-yen coupon should be converted by spend amount');
run(`COUPON_FEED.offers=[{id:'f1',provider:'famipay',brand:'*',rankable:false,title:'抽選',start,end,checkedAt:new Date().toISOString()}];
 const fami={store:'ファミリーマート',aliases:[],payments:[{id:'famipay',n:'FamiPay',r:'0.5%',rankable:true}]};`);
assert.equal(run('couponOffers(fami,"famipay").length'),1,'display-only campaigns stay visible');
assert.equal(run('couponStoreOffer(fami,"famipay")'),null,'display-only campaigns never alter ranking');
console.log('Major Pay campaign eligibility, caps, fixed discounts, provider mapping and display-only safety checks passed');
